### PR TITLE
[JENKINS-32179] Can enable test now

### PR DESCRIPTION
**Pull request by jglick**
Follows up https://github.com/jenkinsci/pipeline-plugin/pull/363.

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
Tests are broken because of mangled snapshots; CC @stephenc.

**Comment by gpkirk** [comment]
Just wondering if the change regarding Jenkins initial run using groovy pipeline parameters is close to being committed and released yet.  Thanks for your attention.

**Comment by jglick** [comment]
@gpkirk I am not sure what you are referring to by that comment. If you know of a specific defect in currently released plugin versions, please file a bug report with complete, minimal, self-contained steps to reproduce from scratch. This PR merely enables a test which had been awaiting some plugin release.

**Comment by recampbell** [comment]
🐝

**Pull request merged**
