### PR TITLE
[JENKINS-31162] Support for Item categorization for MultiBranchProjects

### PR DESCRIPTION
**Pull request by recena**
Moved from https://github.com/jenkinsci/workflow-plugin/pull/376

This PR belongs to this [JENKINS-31162](https://issues.jenkins-ci.org/browse/JENKINS-31162) issue and allows to categorize the Multibranch projects in a right way.

downstream of https://github.com/jenkinsci/cloudbees-folder-plugin/pull/56

@reviewbybees especially @jglick

### CODE REVIEW

**Comment by jglick** [comment]
:bee: though not mergeable until the dependency is released, or you override `getCategoryId` here.

**Comment by recena** [comment]
@jglick Do you agree if we cut a release of `cloudbees-folder-plugin`?

**Comment by jglick** [comment]
Sure, I will do it.

**Comment by jglick** [comment]
5.8 released.

**Pull request merged**
