### PR TITLE
Better behavior when SCMSource.fetch returns null

### PR DESCRIPTION
**Pull request by jglick**
@reviewbybees

### CODE REVIEW

**Comment by recena** [comment]
🐝

**Comment by jglick** [comment]
Tests are broken because of mangled snapshots; CC @stephenc.

**Comment by jglick** [comment]
Re`deploy`ed `branch-api` and `cloudbees-folder` from `master` to see if that fixes test failures.

**Comment by svanoort** [comment]
🐝

**Comment by abayer** [comment]
:bee:

**Pull request merged**
