### PR TITLE
[JENKINS-33819] New API to create WorkflowMultiBranch projects specifying an OrphanedItemStrategy

### PR DESCRIPTION
**Pull request by recena**
[JENKINS-33819](https://issues.jenkins-ci.org/browse/JENKINS-33819)

downstream of https://github.com/jenkinsci/cloudbees-folder-plugin/pull/61
downstream of https://github.com/jenkinsci/branch-api-plugin/pull/41

@reviewbybees

### CODE REVIEW

**Comment by recena** [comment]
Deploying spanshots...

**Comment by jglick** [comment]
As noted in the upstream PRs, using a setter would obviate the need for this PR to even exist.

**Comment by amuniz** [comment]
> As noted in the upstream PRs, using a setter would obviate the need for this PR to even exist.

Why? I think this is still needed. The setter should be called here and not in `OrganizationFolder`, so each `MultiBranchProjectFactory` implementation can decide if inherit the configuration or not.

**Comment by jglick** [comment]
> so each `MultiBranchProjectFactory` implementation can decide if inherit the configuration or not

I do not see any particular reason for a factory to be involved in this decision. If such a reason is found in the future, an API addition could be made for it.

**Comment by recena** [comment]
I agreed with the proposal in this PR, for that reason I sent the PR 😄

**Pull request closed without merging**
